### ISSUE TITLE
bibsonomy template tags break code

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/apis-core#100]
https://github.com/acdh-oeaw/apis-core/commit/da50bb6ffa13c476a4c50e94729eafc7debad406#diff-b790ca2ea13ee6a63566718eb0b505bd introduced bibsonomy template tags but this does not work as long as bibsonomy package is not installed

**Comment by csae8092** [comment]
reomved bibsonomy tag in https://github.com/acdh-oeaw/apis-core/commit/67c0299f85b1ae7a57706f96c6f26b3d10e23b2b

**Comment by sennierer** [comment]
changed the behaviour in 1c560f22511c640ab37dd049f09d4cd10a8bbc10
should work out of the box, only by adding/removing bibsonomy plugin from installed apps
