### ISSUE TITLE
Lat/Long but no maps

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#117]
Sometimes, even though lat and long are entered, the map does not show the location, e.g.

[https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/35644/edit](https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/35644/edit)

**Comment by sennierer** [comment]
Thats because the status of a place has to be set to "distinct" to show the location at the map (I have set the place in the example to distinct, and the location shows now)...we might want to change that though
