### ISSUE TITLE
Collate date views

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#120]
When showing a relation the date is usually shown like this:
09/17/1883
This is not in line with the other views where German standards are used: dd.mm.yyyy and it is irritating

(apart from the known problem that year-only dates are displayed as 01/01/yyyy which is totally confusing)

**Comment by csae8092** [comment]
will switch to german date format soon

**Comment by csae8092** [comment]
done by overriding `LANGUAGE_CODE` in pmb-specific settings-file
