### ISSUE TITLE
Export UTF-8

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#121]
When I export from PMB the result messes up special characters. (Mac), i.e.:
Das MÃ¤rchen
for
Das Märchen
Could that be fixed on the server side?

See:
https://php-de.github.io/jumpto/utf-8/

**Comment by csae8092** [comment]
apis is exporting in utf-8
use [libre-office](https://de.libreoffice.org/download/download/)

**Comment by martinantonmueller** [comment]
True. I did open in Excel and then in LibreOffice and that messed it up already
