### ISSUE TITLE
Layout Tags bug

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#122]
No clue why, but here:
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/4203/edit

![Bildschirmfoto 2019-07-11 um 11 28 04](https://user-images.githubusercontent.com/11441262/61039457-11944c00-a3cf-11e9-8f86-dd91dc67b405.png)

**Comment by csae8092** [comment]
is it just the optics? or is something not working?

**Comment by martinantonmueller** [comment]
Optics!
