### ISSUE TITLE
PMB: Problem with database

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#123]
I cannot access Agnetendorf:
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/735/detail
Server Error 500
as well as Breslau:
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/677/detail
 
and afterwards it was not possible to create a new place

**Comment by csae8092** [comment]
fixed issue; problem was that there was at least one label with no label-type set (which should actually not be possible because this field is mandatory) and might indicate some issue with parsing geonames data
