### ISSUE TITLE
Relation not possible because of error in dropdown field

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#124]
I have a couple named "Schnitzler" and "A. Schnitzler", so no forename except for the A. of the wife. I can not relate them, because neither of them is showing up in the dropdown-list when entering "Schnitzler*"

https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/36675/edit

https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/36677/edit

**Comment by csae8092** [comment]
Try with "Schnitz*" and scroll to the end of the drop down list (more results are only loaded if needed, i.d. you need to scroll down)
related https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/36675/detail
please check if it works and if so, feel free to close the issue

**Comment by martinantonmueller** [comment]
True! It is strange that abbreviations like „Schnitzle*“ work, but not the complete surname. Or is that a feature?

**Comment by sennierer** [comment]
The complete surname also works, you just need to scroll to the end of the page as @csae8092 mentioned. The autocomplete always fetches 20 results from every source and when you scroll to the bottom loads another 20 from every source. As there are more than 20 Schnitzler in the db the one you searched for is in the second "page" of the db results. To sum that up: If you enter "Schnitzler" in the Person autocomplete and scroll to the very bottom, the autocomplete loads more results. The first of these new results is the one you were searching for.

**Comment by martinantonmueller** [comment]
But is it possible to have all the db-entries before alternative offers? Because this is a possible source for duplicates as one does not know when to search for more db-entries?

**Comment by sennierer** [comment]
wee need to change the autocomplete, but yes we could do that. I'll look into it.

**Comment by sennierer** [comment]
created a new issue for the change of the autocomplete #127
