### ISSUE TITLE
How to filter by relation type?

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/apis-core#125]
I *think* this is supposed to work like this:
https://pmb.acdh.oeaw.ac.at/apis/api/relations/personinstitution/?format=json%2Bnet&relation_type__id=1183

But that returns 500 Error.

**Comment by csae8092** [comment]
this is a data problem; related to #126

**Comment by csae8092** [comment]
ok, the netjson renderer threw an error in case of an empty queryset, fixed this now
