### ISSUE TITLE
Ensure relations have a valid relation type

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/apis-core#126]
It looks like not every relation has a valid relation type? E.g. the following has `relation_type: null`:

`https://pmb.acdh.oeaw.ac.at/apis/api/relations/institutionwork/36251`

**Comment by csae8092** [comment]
hm, this should actually not be possible since relation_type is a mandatory field...

**Comment by csae8092** [comment]
I added a relation type now
