### ISSUE TITLE
feature request – usability of relations in edit view

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#128]
The usability would increase (several clicks could be saved) if the view of the relations would be tweaked.

Now in edit view i have to click to see the existing relations and then get the field for adding a new one.

More comfortable would be to have all relations shown all the time (just like in the detail view) and just have a button to add a new relation.

**Comment by csae8092** [comment]
careful what you wish for, because if all relation were expanded you'd need to scroll a lot in case you'd like to add a new Label or Work

**Comment by martinantonmueller** [comment]
ok, I tweak my wish: have the first page of relations expanded…
