### ISSUE TITLE
Cannot select person with no surname in results table

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#129]
If a person is known only by it's given name or the name is not known at all, the table with the results makes it impossible to select that very person. I.e.:
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/list/?page=411
final lines. 

Solution would be to make the "–" a link to the entry

**Comment by csae8092** [comment]
For a quick solution, you can add the following query-param `&columns=id` to the URL like in 
`https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/list/?page=411&columns=id`
This will display the ID of the entity as a link to the detail view of the entity. But maybe in not too far future we might come up with a slightly more elegant solution...

**Comment by csae8092** [comment]
fixed with https://github.com/acdh-oeaw/apis-webpage-base/commit/470a1b6ea83441697ece52239bb0e38a624dd650

(id field can now be selected as additional column)
