### ISSUE TITLE
URIs – Delete and Merge behaviour

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#130]
The following features are necessary:
+ Ability to delete URIs
+ When merging two entries the URIs are not added to the URI-field. Thus it does not recognize already existing entries based on the URIs.

**Comment by sennierer** [comment]
When merging URIs are now moved to the URIs field.
There is the possibility to search for URIs and delete them: https://pmb.acdh.oeaw.ac.at/apis/metainfo/apis/metainfo/uri/
We might want to move that to the entities forms, but for the moment that should be sufficient. Closing
