### ISSUE TITLE
prosopgraphAPI renderer throws error 

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/apis-core#131]
In instances without highlighter package, the prosopgraphAPI renderer does not work, see e.g.
https://pmb.acdh.oeaw.ac.at/apis/api2/entity/2132/?format=json%2Bprosop because of if 
``` python
len(rel_1["annotation"]) > 0:
    s['statementContent'] = rel_1["annotation"][0]["text"]
```

https://github.com/acdh-oeaw/apis-core/blob/3c21d71e2b4715f360185d62897e21ef5781e9e2/apis_core/apis_entities/api_renderers.py#L231

**Comment by sennierer** [comment]
seems to be fixed, closing
