### ISSUE TITLE
Wrong parsing of of dates

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#132]
There are two annoying misbehaviours:

1) Even though only a year is entered it is usually displayed as "01.01.YYYY"

2) Weirder is what happens when one enters e.g.: 

> <1914-08>August 1914
because that displays as:
> 24.08.1914
see: https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/34344/detail

**Comment by csae8092** [comment]
weired indeed @steffres I can you please look into this?
@martinantonmueller for expressing a time span (like august) as iso-date, why not set start-date 1914-08-01 and end-date 1914-08-31?

@sennierer @steffres I guess we need to display also the written date (or only the written date) for start/end dates in relations, maybe with tooltip for iso-date

**Comment by martinantonmueller** [comment]
Usually I do. But sometimes I only know somebody was in that month in a certain place, not the exact date.

**Comment by martinantonmueller** [comment]
> currently we use the iso-dates to allow for ordering of the tables

It's perfectly fine to use ISO-Dates for ordering, but the display is something different. It cannot (and currently does) show dates which are wrong –

**Comment by csae8092** [comment]
@sennierer boils down to an additional column? maybe a combined on of start- and end date called duration or so? implemented as templateColumn? or is it possible to use a templateColumn also for (correct) sorting, which would be better (i.e. show the written date but use the iso date)

**Comment by sennierer** [comment]
> @sennierer boils down to an additional column? maybe a combined one of start- and end date called duration or so? implemented as templateColumn? or is it possible to use a templateColumn also for (correct) sorting, which would be better (i.e. show the written date but use the iso date)

I guess two columns would be rather confusing. I'll have a look how difficult it is to sort on a different attribute in the django tables

**Comment by sennierer** [comment]
closing while investigating #133

**Comment by csae8092** [comment]
reopen issued because the actual problem - the obvious strange date parsing - is not covered by #133
