### ISSUE TITLE
filter tables on iso-dates while showing written dates

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core#133]
we should display the written dates everywhere (as it is the date users entered) and use the computed iso-dates only in the background. See #132 for discussion.

**Comment by csae8092** [comment]
needed for
* tables in relations in entity detail https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/2128/detail
* and edit views, https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/2128/detail
* tables in listview for entities https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/list/ 
* and relations listviews https://pmb.acdh.oeaw.ac.at/apis/relations/personperson/list/

**Comment by steffres** [comment]
In all the outlined views now there is only written dates displayed. I had it already pushed before but forgot the relations overview, which I included in most recent commit [9d01e00](https://github.com/acdh-oeaw/apis-core/commit/9d01e0013233965fcad96c751fccdc6a8cd99ead)
