### ISSUE TITLE
provide helptexts for filter/search forms in list views

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/apis-core#134]
as of now, only a handful apis-experts know that you can use e.g. * to search case insensitive with fuzzy string match. While reworking the filter @steffres please provide some helptexts

**Comment by steffres** [comment]
Yup, will be included when I finished polishing my parts and pushing them to a new branch as agreed before.

**Comment by skurzinz** [comment]
What's the status of this? I just discovered that searching for *bla bla* does not find the entity called *bla  blah* (with two spaces in its name), even if it finds "aba bla blap" and others.

**Comment by steffres** [comment]
Triaged due to resoure limitations.
