### ISSUE TITLE
do not remove internal uris when new uris are linked

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core#135]
we currently remove internal identifiers when we add new external uris >> we shouldnt do that

**Comment by csae8092** [comment]
https://pmb.acdh.oeaw.ac.at/apis/api2/uri?uri=Ottakringer_Brauerei

**Comment by sennierer** [comment]
internal uris were not deleted when new ones were linked, but only created when no external one existed. Removed that function in 67368443155bf09eb6830c5bc21915b1f10d0a07
internal uris should now be created for every entity
