### ISSUE TITLE
Duplicate Labels when merging

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#150]
The merge-function could be improved when labels would be checked if they already exist. Currently they're duplicated. If the Name is identical even the "Legacy name (merge)"-label doesn't really make sense
-- | --

**Comment by sennierer** [comment]
That depends. The legacy name label makes it explicit what the name of the previous entities was. If we set it only if the names change, you have to assume that they were the same

**Comment by martinantonmueller** [comment]
Let's go through this:

1) Entry A and entry B are named the same, they are merged. What information-value is there to know that once there were two entries of the same name? E.g. take Italien, where several merges happened because it didn't treat the geonames ID properly before:

https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/40306/detail

2) Entry A and B are named differently. Then it is okay to conserve the name.

P.S. And a real life user experience: As there is no merge function in "Places" edit-view but only in the search-page I usually rename entry B (say Danzig) to the Name of entry A (say Gdansk) so they show up in the same list and only then I can merge them.

**Comment by sennierer** [comment]
These are two issues: One is the problem of a missing merge field in the place edit views. I created a seperate issue for that: #182 
The other one is regarding the duplicates in the labels. There is already an issue for that: #177 
Closing this one.
