### ISSUE TITLE
Feature suggestion: Cleaner URIs

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#151]
It would be nice to have this URI shortened to have just the number in the end:
> https://pmb.acdh.oeaw.ac.at/apis/entities/entity/work/31857/detail

like this:

> https://pmb.acdh.oeaw.ac.at/apis/entities/entity/work/31857

and since we're at it and since the numbers are actually unique event though they are different classes, this would also be a nice feature:

> https://pmb.acdh.oeaw.ac.at/apis/31857

or

> https://pmb.acdh.oeaw.ac.at/31857

i.e. be able to access all numbers without clarifying which class they are

**Comment by sennierer** [comment]
I would opt for something that at least contains the entity type:
https://pmb.acdh.oeaw.ac.at/work/31857

or even better contains the title/name instead of the id:
https://pmb.acdh.oeaw.ac.at/work/zwei_gluckliche_tage

using numbers (or the start_date) to make them unique if needed:
https://pmb.acdh.oeaw.ac.at/work/zwei_gluckliche_tage#2

**Comment by sennierer** [comment]
to make it concise and easy I decided for {BASE_URL}/entity/ID
E.g. https://pmb.acdh.oeaw.ac.at/entity/31857

**Comment by csae8092** [comment]
> to make it concise and easy I decided for {BASE_URL}/entity/ID
> E.g. https://pmb.acdh.oeaw.ac.at/entity/31857

does this involve a change/rewrite of already existing non external URIs like e.g. those eos.arz... or whatever other uris we have in all the apis projects using some made up base-uri and the entities ID? Or should someone provide a script which checks all existing URIs and changes them in a clever way?

**Comment by sennierer** [comment]
no, we need to do that manually.
I started with cleaning the URIs for apis-edits. But I guess we need to decided per project how to proceed...for PMB for example we might not want to delete the old URIs - as someone could already have used one of the old URIs somewhere - but rather additionally add the new cleaner URIs?

**Comment by vronk** [comment]
> or even better contains the title/name instead of the id:
> https://pmb.acdh.oeaw.ac.at/work/zwei_gluckliche_tage
> 

semantic clutter in URIs?
please, no.

**Comment by sennierer** [comment]
yes, already decided against it, its {BASE_URL}/entity/ID for all the new entities and we change to this structure in the instances were URIs havent been used and/or published yet.
For projects like PMB we need to discuss whether we change uris or only add the new style uris and keep the old ones.
The old style uris apis/api2/entity will still resolve, but if we remove the old style uris the RDFs will miss the same as links

**Comment by martinantonmueller** [comment]
Currently I believe it would still be possible to change PMB-URIs. But that is my opinion and @ingoboerner has a say in it just as much as I have.
