### ISSUE TITLE
translation for labels

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#156]
it would be nice to be able to store labels in german and have their english equivalents. e.g. the import usually imports "alternative Name" while the German label is "Variante". In an ideal word those two are the same except for the language.

**Comment by skurzinz** [comment]
Just my 2¢: I would not go for "Variante", as this is even more ambiguous (no 1:1 relation to the concept of "name")

**Comment by martinantonmueller** [comment]
duly noted: it is now "Namensvariante"

**Comment by sennierer** [comment]
the import can be configured. whatever it uses as a label type can be set in the RDF import configuration. the label types can even be changed afterwards in the admin backend. translating the vocabularies is of scope for the moment. closing it for the moment.
