### ISSUE TITLE
URI used by other instance

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#158]
We have an entry named "Orahovica". When using the map to find geonames-URI it finds the right place. But selecting it leads to an error. Same when one trys to create Orahovica with the import-tool on the search-site.

Request Method: | GET
-- | --
https://pmb.acdh.oeaw.ac.at/apis/entities/resolve/place/42943/sws.geonames.org/3194064/
2.1.2
ValueError
URI used by other instance
/var/www/html/apis-webpage-base/apis_core/helper_functions/RDFParser.py in _exist, line 103
/usr/bin/python3
3.6.8
['/var/www/html/apis-webpage-base',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  '/var/www/html',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf']
Sa, 30 Nov 2019 09:04:52 +0000

Environment:

Request Method: GET
Request URL: https://pmb.acdh.oeaw.ac.at/apis/entities/resolve/place/42943/sws.geonames.org/3194064/

Django Version: 2.1.2
Python Version: 3.6.8
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'reversion',
 'reversion_compare',
 'crispy_forms',
 'django_filters',
 'django_tables2',
 'rest_framework',
 'webpage',
 'browsing',
 'django_extensions',
 'apis_core.apis_entities',
 'apis_core.apis_metainfo',
 'apis_core.apis_relations',
 'apis_core.apis_vocabularies',
 'apis_core.apis_labels',
 'rest_framework.authtoken',
 'rest_framework_swagger',
 'drf_yasg',
 'guardian',
 'charts',
 'infos']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'reversion.middleware.RevisionMiddleware']

Traceback:

File "/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "/var/www/html/apis-webpage-base/apis_core/apis_entities/views.py" in resolve_ambigue_place
  446.         pl_n = RDFParser(uri, kind='Place').create_objct()

File "/var/www/html/apis-webpage-base/apis_core/helper_functions/RDFParser.py" in __init__
  456.         test = self._exist(self.uri, uri_check=uri_check)

File "/var/www/html/apis-webpage-base/apis_core/helper_functions/RDFParser.py" in _exist
  103.                     raise ValueError("URI used by other instance")

Exception Type: ValueError at /apis/entities/resolve/place/42943/sws.geonames.org/3194064/
Exception Value: URI used by other instance

**Comment by sennierer** [comment]
can you try to save the instance again in 30 minutes? Parsing RDFs takes some time and in order to not save one and the same entity twice the first thing the system does is "reserving" the URI. The object storing these reserved URIs is cleared every 30 minutes. So please try to save it in 30 minutes again. If it doesnt save, please report here the error message of your first attempt to save it.

**Comment by martinantonmueller** [comment]
This is the error code. So i presume it is the same fix you applied yesterday that will solve this problem as well:

`

Request Method: | GET
-- | --
https://pmb.acdh.oeaw.ac.at/apis/entities/resolve/place/42943/sws.geonames.org/3194064/
2.1.2
AttributeError
'NoneType' object has no attribute 'save'
/var/www/html/apis-webpage-base/apis_core/apis_entities/views.py in resolve_ambigue_place, line 447
/usr/bin/python3
3.6.8
['/var/www/html/apis-webpage-base',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  '/var/www/html',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/odf']
So, 1 Dez 2019 18:33:10 +0000

`

**Comment by sennierer** [comment]
yes, should be fixed now
