### ISSUE TITLE
Place Nonetype has no attribute to save

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#159]
Paracelsus was born in Egg (Schwyz, Switzerland). As there are many Egg's I created a place Egg and then tried to use the map with "Egg SZ" to locate the right one. It's right there and I can select the pin but afterwards there is this error:

> Environment:
> 
> 
> Request Method: GET
> Request URL: https://pmb.acdh.oeaw.ac.at/apis/entities/resolve/place/42951/sws.geonames.org/7669543/
> 
> Django Version: 2.1.2
> Python Version: 3.6.8
> Installed Applications:
> ['dal',
>  'dal_select2',
>  'django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'reversion',
>  'reversion_compare',
>  'crispy_forms',
>  'django_filters',
>  'django_tables2',
>  'rest_framework',
>  'webpage',
>  'browsing',
>  'django_extensions',
>  'apis_core.apis_entities',
>  'apis_core.apis_metainfo',
>  'apis_core.apis_relations',
>  'apis_core.apis_vocabularies',
>  'apis_core.apis_labels',
>  'rest_framework.authtoken',
>  'rest_framework_swagger',
>  'drf_yasg',
>  'guardian',
>  'charts',
>  'infos']
> Installed Middleware:
> ['corsheaders.middleware.CorsMiddleware',
>  'django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'reversion.middleware.RevisionMiddleware']
> 
> 
> 
> Traceback:
> 
> File "/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
>   34.             response = get_response(request)
> 
> File "/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
>   126.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
>   124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
> File "/var/www/html/apis-webpage-base/myenv/lib/python3.6/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
>   21.                 return view_func(request, *args, **kwargs)
> 
> File "/var/www/html/apis-webpage-base/apis_core/apis_entities/views.py" in resolve_ambigue_place
>   447.         pl_n_1 = pl_n.save()
> 
> Exception Type: AttributeError at /apis/entities/resolve/place/42951/sws.geonames.org/7669543/
> Exception Value: 'NoneType' object has no attribute 'save'

**Comment by sennierer** [comment]
resolved the issue in 8b7a5096f94f0e4816442c9c5556849178805372
deploying it on monday
