### ISSUE TITLE
how to handle parallel entries in MPR and OeBL Apis?

### ISSUE THREAD

**Issue by sviatoplok** [acdh-oeaw/apis-core#163]
If we have entries on identical entities such as

https://apis.acdh.oeaw.ac.at/person/68353 and https://mpr.acdh.oeaw.ac.at/apis/entities/entity/person/4235/edit

in APIS and in MRP

what do we do?

**Comment by sennierer** [comment]
related to #172 
We will include other APIS instances in the autocompletes and allow to import from these instances. The import will automatically create corresponding URIs
