### ISSUE TITLE
Automatic import of place not working

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#165]
In relation to the previous issue https://github.com/acdh-oeaw/apis-core/issues/164
I have to say that this appears to be a greater bug. 
Work->
New relation to place ->
Place does not exist ->
Choose geoNames suggestion
--> It loads but then the button is grayed out and no place created
<img width="656" alt="Bildschirmfoto 2020-01-09 um 12 10 30" src="https://user-images.githubusercontent.com/11441262/72063128-7a567580-32d9-11ea-8c35-c9d9a7b82779.png">

**Comment by sennierer** [comment]
works in the new version, closing for now
