### ISSUE TITLE
500 error when selecting rdf+xml in REST framework

### ISSUE THREAD

**Issue by AlexanderWatzinger** [acdh-oeaw/apis-core#170]
At some entries the rdf+xml parsing doesn't seem to work (with some it works) and I get a "Server Error (500)" page.

E.g. with the entry "Staatliche Museen zu Berlin" (id 132780)

Steps to reproduce:
1) Visiting URL: https://apis.acdh.oeaw.ac.at/apis/api2/entity/132780
2) Choosing option "rdf+xml" at the "GET" drop down 

After that the sites redirects to https://apis.acdh.oeaw.ac.at/apis/api2/entity/132780/?format=rdf%2Bxml and displays an 500 error.

**Comment by sennierer** [comment]
resolved with https://github.com/acdh-oeaw/apis-core/commit/6eece6b0d468c433a8f736c0bfd0db6eee849a7f
