### ISSUE TITLE
sorting of relations based on date is not working

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#179]
the sorting of the relations should not happen based on the written date but on the iso-date. though this is the link one get's when clicking on 'End' on top of relations:

https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/213/edit?PePl-sort=end_date_written

**Comment by sennierer** [comment]
yes, sorting should work on the sort date, while we display the written date

**Comment by sennierer** [comment]
this should be resolved in f99e4732c6a7a3282d6eb2f37fae3b4a4a545825
