### ISSUE TITLE
Strange first entry in relations list

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#184]
When I create a relation to a place already existing entries in the database are not listed as first results but only from 2 onwards. Result 1 can not be selected:

<img width="279" alt="Bildschirmfoto 2020-01-29 um 15 49 24" src="https://user-images.githubusercontent.com/11441262/73367020-296de780-42af-11ea-980d-bcf6f9c89d2f.png">

**Comment by sennierer** [comment]
Yes, sorry. We should have communicated that change in behaviour: 

We had problems with our reference resource indexes in stanbol not being complete and/or up-to-date. As a consequence we allow now to paste URLs from reference resources directly in the autocomplete fields. As they are not in the index we must allow to add new entries in the autocomplete. Therefore the first entry in the autocompletes is now whatever you entered in the search field. If you pasted e.g. an URL from GND the server will accept it and save the entity. If you enter the string "Berlin" it will tell you that "Berlin" is not an URL and that you either need to select an entry or use an URL. If you paste any URL e.g. http://test.at, the server will complain that test.at is not a configured URL.

This means that from now on you can either:
* search for entries as you did before and select one of the entries that start with "db", "Geonames" etc.
* or head over to Geonames, GND, or lobid, search for your entity, copy the link, paste it to the autocompletes field and save the form.

But you can not search for a string and select the first entry, as it is only your query string.

**Comment by martinantonmueller** [comment]
Ok! But wouldn't some kind of "starts-with(.,'https:') or sws:// make sense? so if I enter something that actually is an URI i can select it but not if it is not?
