### ISSUE TITLE
Font used apparently without big Umlauts (Ä, Ö)

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#187]
Cf.
<img width="661" alt="Bildschirmfoto 2020-02-06 um 11 41 56" src="https://user-images.githubusercontent.com/11441262/73929977-11f9b480-48d6-11ea-8540-8ca55716fa74.png">

**Comment by sennierer** [comment]
Was not the font, but the line height to small for the dots
