### ISSUE TITLE
Saving a relation doesn't work 

### ISSUE THREAD

**Issue by steffres** [acdh-oeaw/apis-core#194]
In master as in coladay branch with recent commits (apis-core at 5ee15a1 , apis-webpage-base at 257c42d ), creating or modifying a relation via the relation forms doesn't work. 

No error is thrown on the server via the python stdout but in the browser's JS console the following is returned:

```
Uncaught TypeError: Cannot read property 'tt_instance_detail' of undefined
    at EntityRelationForm_response (edit:1422)
    at Object.<anonymous> (edit:91)
    at u (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at k (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
```

### steps to reproduce

If editing an existing relation, clicking on the 'create/modify' button only disables the button:

![image](https://user-images.githubusercontent.com/35728628/75905745-b58ea400-5e45-11ea-9bdb-d054c5acd42d.png)

If adding a new relation, the help_text underneath returns error message 
'Invalid value: <span ><small>db</small> Work_test_0</span>, use either URLs or select a value'

Both if the related entity exists within apis db

![image](https://user-images.githubusercontent.com/35728628/75906072-5c734000-5e46-11ea-870b-711ffca7774b.png)

or is a gnd referenced one:

![image](https://user-images.githubusercontent.com/35728628/75906048-52514180-5e46-11ea-83fa-22f6508bc766.png)

**Comment by sennierer** [comment]
thats due to a bug in select2.js that is shipped with DAL that makes select2 replace the id of a setting with the text of the entry. Thats why it claims that the span is not an acceptable value.
For the docker instances we solve that with the following line:
```
RUN sed -i '56 s/value.id = value.text;/value.id = value.id;/' /usr/local/lib/python3.6/site-packages/dal_select2/static/autocomplete_light/select2.js
```
so basically we replace value.text with value id in line 56 of the DAL select2.js file

**Comment by steffres** [comment]
Ah yeah, forgot about that. Thanks.
