### ISSUE TITLE
implement entity-merge-function

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/apis-core#2]
Select two entities and merge theme (via GUI)
* remove one of the two selected entities
* (re)link all related objects from the deleted to the preserved entity
  * optionally: allow merge of more then two entities

**Comment by sennierer** [comment]
The TempEntityClass merge_with(entities) function implemented in  https://github.com/acdh-oeaw/apis-core/commit/3145f57e7e433c5a982415e928213e26573990c9 allows to merge the selected object with either one or a list of objects. Preserves the relations and the labels, adds the names of the objects as "legacy name (merge)" labels and the URIs as "legacy URI (merge)" labels.
The function still needs implementation in the GUI though.
