### ISSUE TITLE
move most of js to cdn and keep only needed local

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core#20]
there is no really elegant way to import needed js when installing a package from pypi. we should therefore load all the js libraries needed via cdn and include only the really needed things directly in the package (fork from linkurious)

**Comment by csae8092** [comment]
besides linkurious related libraries, all other js/css libs are now loaded from cdn, see
`apis_core\apis_entities\templates\apis_templatetag.html` 
I guess with this, we can close this issue
