### ISSUE TITLE
merge function, original uri

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#200]
I thought this was solved, but it doesn't seem to work anymore: I've just merged two persons,

https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/2226/edit
and
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/26735/edit

to 2226. It was agreed upon that the URI of the second would still be accessible, but it is not.

**Comment by sennierer** [comment]
i tested it and the merging is still keeping the URIs. Possibly the two entities did not have decent pmb URIs. The 2226 certainly does not. In earlier versions we added APIS specific URIs only for those entities were we had no other URI. I'll add new style URIs to all PMB instances later on (https://pmb.acdh.oeaw.ac.at/entity/{ID})

**Comment by martinantonmueller** [comment]
Thank you!

**Comment by sennierer** [comment]
Now every entity in pmb has the new URI https://pmb.acdh.oeaw.ac.at/entity/{ID}. These URIs resolve and when merged should be kept. When we have decided if we can delete the old style URIs I can still remove them. Closing for now, please reopen in case the URIs are not kept when merging.
