### ISSUE TITLE
provide possibility to download vocabularies

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/apis-core#202]
requested by @martinantonmueller

**Comment by csae8092** [comment]
should be possible now https://gitlab.com/acdh-oeaw/apis/apis-core/-/commit/ae1caff0a860fa3cc861580dbbd958ada3312097

e.g. {project-base-url}apis/api/vocabularies/download/{vocabClassName/
e.g.https://pmb/apis/api/vocabularies/download/worktype/

triggers the download of a csv with columns  ['id', 'name', 'parent_class']

**Comment by martinantonmueller** [comment]
I suppose this might take a while to be functional, because:
https://pmb.acdh.oeaw.ac.at/apis/api/vocabularies/download/worktype/
does not work

**Comment by csae8092** [comment]
yes, after pushing changes to the apis-code-repos, a pipline is triggered which runs some tests and (if the they pass) deploy the new code version to all the millions of apis-instances we are running 
this takes a while (~ 30 min)
