### ISSUE TITLE
Change the relationtype search field to exact search 

### ISSUE THREAD

**Issue by steffres** [acdh-oeaw/apis-core#206]
Currently in the relation edit form, the searches behave differently on relationtype and on entities. On relationtype any textual input is search for in an 'icontains' manner, while on searching for entities it is done as 'iexact'.

In order to be consistent overall, the relationtype search field should also be changed to 'iexact' (since changing the entity search to 'icontains' returns too many false positives).

**Comment by sennierer** [comment]
opted for icontains for the moment https://github.com/acdh-oeaw/apis-core/commit/f93e68c625c28a453ff9610619509a203605bb29
