### ISSUE TITLE
Desired behaviour? "Lugano*" has less results than "Lugano" 

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#208]
When searching for "Lugano" in PMB one gets six results because five places have labels containing name of place plus "bei Lugano". When searching for "Lugano*" the amount of results is reduced to two, as "Blablabla bei Lugano" is not included anymore. I'm not sure whether this is the desired behaviour.

**Comment by sennierer** [comment]
yes, the wildcard stands for "one character or more" so Lugano* is Lugano plus at least one character
