### ISSUE TITLE
Bibsonomy: Entering any URL in the Bibs url text field of the pop-up form does not return any results

### ISSUE THREAD

**Issue by steffres** [acdh-oeaw/apis-core#217]
When entering any URL, it displays 'The results could not be loaded'

![image](https://user-images.githubusercontent.com/35728628/85292100-b0f50680-b49b-11ea-8dd7-3c6413c58514.png)

Does not matter if the URL does reference a bibsonomy URL or not. 

Easily reproducable by entering any URL.

It produces following error output:
```
Internal Server Error: /bibsonomy/autocomplete/
Traceback (most recent call last):
  File "/home/steff-vm/coladay/dev_instance/myenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/steff-vm/coladay/dev_instance/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/steff-vm/coladay/dev_instance/myenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/steff-vm/coladay/dev_instance/myenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/steff-vm/coladay/dev_instance/myenv/lib/python3.6/site-packages/dal/views.py", line 49, in dispatch
    return super(ViewMixin, self).dispatch(request, *args, **kwargs)
  File "/home/steff-vm/coladay/dev_instance/myenv/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/steff-vm/coladay/dev_instance/root_coladay_dev/apis-webpage-base/apis_bibsonomy/autocompletes.py", line 46, in get
    if c['type'] == 'bibsonomy':
TypeError: string indices must be integers
```

Hence the error lies in the method `get` of the class `BibsonomyAutocomplete` 
(File: apis_bibsonomy/autocompletes.py, line number 46):

```
                 .....
45:            for idx, c in enumerate(self.conf):
46:                if c['type'] == 'bibsonomy':
                          .....
```
There the variable `c` is actually a string with content 'url', instead of seemingly a dict which the code would expect.
`c` itself is a value of a dict stored in `self.conf`

`self.conf` is a dict saved into `self` on line 68:
```
self.conf = getattr(settings, "APIS_BIBSONOMY", None)
```
and `settings` itself is imported via
```
from django.conf import settings
```
From which I could not deduce further where it actually comes from, but grep'ing for `APIS_BIBSONOMY` shows that in my local case it's either
```
apis-webpage/apis/settings/dev.py
apis-webpage/apis/settings/server.py
```
So it surely comes from dev.py in my local setup and on the production server from server.py.

The dict defined there stores credentials for bibsonomy access as: `url, user, API key, group`.

So my interpretations is that in the loop on line 45 of file `autocompletes.py` the code is designed to search through the whole settings file, aiming to extract the dict with access values, while actually on line 68, it is already given the relevant dict, which then is searches through needlessly?

**Comment by steffres** [comment]
Maybe it's also due to an outdated settings file on my branch, so just to be clear my local dev.py for example has the following content structure:

```
....
EMAIL_HOST = 'smtp.oeaw.ac.at'

SERVER_EMAIL = XXX

ADMINS = XXX

APIS_BIBSONOMY = {
    'url': XXX,
    'user': XXX,
    'API key': XXX,
    'group': XXX
}

APIS_RELATIONS_FILTER_EXCLUDE += ['annotation', ]
APIS_COMPONENTS = ['apis_highlighter']
....
```

**Comment by sennierer** [comment]
yes, the settings file was outdated. Given the fact that we allow for multiple endpoints now it needs to be a list of dicts and as you can also use zotero as endpoint you need to set a type (```'type': 'bibsonomy'```).
Also: the autocomplete just talkes the title of the publication, not the url.
