### ISSUE TITLE
[coladay] annotations seem to be off by one character from time to time

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core#230]
seems to be related to newline characters

**Comment by sennierer** [comment]
example: https://sola.acdh-dev.oeaw.ac.at/apis/api/HLTextHighlighter/1025/?types=97,41&users_show=1,2,3,4,5,7,8,9,10,15,16,17&types=97,41

**Comment by stefanprobst** [comment]
looks like this is still an issue

**Comment by sennierer** [comment]
resolved by 6e7afd40ef1c056d496bb324ba2b8ebe9cc071e8
