### ISSUE TITLE
Geonames Import

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#231]
I can't automatically create:

https://www.geonames.org/2653265/chelsea.html

probably because that is not in the geonames-dump. But can that be?

**Comment by sennierer** [comment]
when using the relation forms you can just paste the link to the rdf even if it is not in the dump: https://sws.geonames.org/2653265/about.rdf
Already did this for chelsea: https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/46895/edit

However, that should be enabled for the simple create form as well. I will addd another issue.
