### ISSUE TITLE
filter on array fields should accept `__in` queries

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/apis-core#237]
filter on array fields should accept `__in` operator as a query param, e.g. `?id__in=1,2,3` or `?topic__in=1,2,3,4`

**Comment by stefanprobst** [comment]
what *does* work though is `https://sola.acdh-dev.oeaw.ac.at/apis/api/entities/passage/?topic=84&topic=126`

**Comment by sennierer** [comment]
There is an issue with [django-filters](https://github.com/carltongibson/django-filter/issues/1103) that is preventing the __in filter for m2m fields for the easiest method of registering filters in an DRF GenericView Class. I will rework the function for creating and registering the filters so we can use the __in filter throughout the API, but for the moment only the workaround mentioned above is working.

**Comment by stefanprobst** [comment]
personally, i'm totally fine with the long form `?topic=84&topic=126` syntax - we should just agree on what we want to support and stick to it

**Comment by sennierer** [comment]
we will keep the support for ```?topic=84&topic=126```. However, for consistency we will additionally add the ```__in``` operator also for m2m fields (currently only working for fk) at a later stage.
closing for now
