### ISSUE TITLE
[coladay] annotated texts should not contain inline styles

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/apis-core#238]
annotated texts, i.e. from `/metainfo/text/:id/?inline_annotations=true?highlight=true` sometimes contain inline styles. these should not be included in the response payload.

examples:
```html
<span style='margin: 0cm; font-size: medium; font-family: "Times New Roman", serif; text-align: justify;' />
<span style="background-color: rgb(255, 255, 0);" />
```

for yellow background see e.g.
https://sola.acdh-dev.oeaw.ac.at/apis/api/metainfo/text/2384/?inline_annotations=true&highlight=true
https://sola.acdh-dev.oeaw.ac.at/apis/api/metainfo/text/2259/?inline_annotations=true&highlight=true
https://sola.acdh-dev.oeaw.ac.at/apis/api/metainfo/text/2259/?inline_annotations=true&highlight=true

for font size see e.g.
https://sola.acdh-dev.oeaw.ac.at/apis/api/metainfo/text/2207/?inline_annotations=true&highlight=true

**Comment by sennierer** [comment]
related to #241
