### ISSUE TITLE
request for annotated text can crash server

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/apis-core#239]
e.g. https://sola.acdh-dev.oeaw.ac.at/apis/api/metainfo/text/51/?inline_annotations=true&highlight=true

```
TypeError cannot unpack non-iterable NoneType object
```

**Comment by stefanprobst** [comment]
fyi this is still happening

**Comment by sennierer** [comment]
fixed that locally until CI pipeline is up and running again
