### ISSUE TITLE
provide info on reference location in GET /bibsonomy/save_get

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/apis-core#246]
the bibsonomy endpoint allows retrieving references placed on an entity, and/or on entity attributes. this can be configured via the `?attribute="all"|"include"|undefined` parameter.
however, the endpoint returns a flat array of references, and it is not obvious which have been referenced by the entity, and which have been referenced by an entity attribute (and *which* attribute).

it is e.g. not clear to me, where the results of https://sola.acdh-dev.oeaw.ac.at/bibsonomy/save_get/?contenttype=passage&object_pk=391&attribute=include are referenced on the entity/entityattributes.

(i might be misunderstanding how this is supposed to work though)

**Comment by sennierer** [comment]
no, thats correct, I will add a relation object to the entity and attribute to the serializer

**Comment by sennierer** [comment]
resolved in 7b2807fea8262a7cfb500268e90bc5bef0b85369
return includes now a "attribute" attribute that is either ´´´null´´´ when the reference is attached to the entity or the attribute it is attached to
