### ISSUE TITLE
provide option to format bibsonomy refs with citation style

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/apis-core#248]
currently, the bibsonomy endpoints return json, which is fine. it would be cool to have the option to retrieve the references as preformatted html, following one of supported citation styles

**Comment by skurzinz** [comment]
Would be cool. https://de.wikipedia.org/wiki/Citation_Style_Language would be a natural candidate for formats that are available and implemented for other sources. Zotero, which I presume is also supported by APIS, plays nicely w/ CSL.

**Comment by sennierer** [comment]
yes, we already decided to implement CSL and allow to set the style used somewhere in the settings.
Just to remember: https://github.com/brechtm/citeproc-py
