### ISSUE TITLE
clarify response shape for annotations

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/apis-core#249]
annotations on `/metainfo/text` sometimes are returned as an `Array<Annotation>`, sometimes as `Array<string, Array<Annotation>>`, where the string is the html string.

example for the first:
https://sola.acdh-dev.oeaw.ac.at/apis/api/metainfo/text/1275/?inline_annotations=true&highlight=true

example for the second:
https://sola.acdh-dev.oeaw.ac.at/apis/api/metainfo/text/5/?inline_annotations=true&highlight=true

**Comment by sennierer** [comment]
Closing this as the the [changed] urls both deliver an arraz of annotation objects of the same shape.

https://sola.acdh-dev.oeaw.ac.at/apis/api/apis_metainfo/text/5/?inline_annotations=true&highlight=true
https://sola.acdh-dev.oeaw.ac.at/apis/api/apis_metainfo/text/1275/?inline_annotations=true&highlight=true
