### ISSUE TITLE
Problems with geoNames import

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#250]
It appears that some smaller geoNames-places are excluded from import possibility. 
Take Cowling:
https://sws.geonames.org/11593148/about.rdf
when pasted into the place-import-field it doesn't show.

Cowling has it's own Wiki-entry:
https://en.wikipedia.org/wiki/Cowling,_Craven

**Comment by sennierer** [comment]
This is the case as our index of geonames is unfortunately not complete and also old. However, that said when creating the relation to the person you can just paste the geonames url in the place field of the relation and select the url (even if there is no result). The system will just grab the RDF and parse it to the db...as done here: https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/48609/edit

Please note: pasting an url is currently only possible when creating a relation, if you try to create the place from within the list of places this is not possible (we will include that soon though)
