### ISSUE TITLE
user interaction with networks view in apis-hub does not allow to turn network

### ISSUE THREAD

**Issue by GVogeler** [acdh-oeaw/apis-core#253]
Wen creating a 1000 entities arbitrary person network on https://apis-hub.acdh-dev.oeaw.ac.at/networks the result is obivously three dimensional (ovelap of nodes), I cannot interact with the third dimension in the browser (FF 80.0.1, chrome), i.e. turning the network with the mouse. Is there only a description missing, how to achieve this, can this be a considered a bug, or is it feature request?

**Comment by stefanprobst** [comment]
not sure i 100% understand the question. 2d/3d view can be toggled in the "Options" popup in the bottom status bar. in 3d, you should be able to rotate the graph by dragging the mouse.

**Comment by GVogeler** [comment]
Thanks, the hint on selecting "3D" as option missing.
