### ISSUE TITLE
incorrect related entities in entity.relations

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/apis-core#264]
`/entities/:entitytype/:id/` include `relations[]`, which include info about the `relation_type` and the `related_entity`. for some types of relation, the included related entity refers back to the entity, instead of the object of the relation.

example PassagePublication relation: passage id 413 has relations where all related entities are id 413

```
curl "https://sola.acdh-dev.oeaw.ac.at/apis/api/entities/passage/413/" | jq '.relations[].related_entity.id'
413
413
413
413
413
```

this however is fine:
```
curl "https://sola.acdh-dev.oeaw.ac.at/apis/api/entities/publication/1261/" | jq '.relations[].related_entity.id'
1264
1266
1268
1270
1272
1274
1276
1278
1263
```

=> `PersonPublication` relation on `publication` will include person as related entity, but `PassagePublication` relation on `passage` includes passage, not publication as related entity

**Comment by sennierer** [comment]
there was an issue with the comparison of the primary keys of the two related entities in a relation. should be resolved now

**Comment by steffres** [comment]
An error is thrown when accessing any entity via REST API, e.g. https://sola.acdh-dev.oeaw.ac.at/apis/api/entities/person/

The error message is `tuple index out of range` and is thrown at https://github.com/acdh-oeaw/apis-core/blob/5348eecb79d38717bc5848b54ff69de33ab7bced/apis_core/api_routers.py#L346
When debugging I could see that in that function the param `args` is an empty tuple. 

Unfortunately a restart of the applications mitigates this error - which makes investigation harder. It is unclear to me which factors after a restart then lead to this error.

**Comment by steffres** [comment]
Stupid me. Was a cache issue. Deleting it in my browser made it work.
