### ISSUE TITLE
make TEI serialization valid

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/apis-core#270]
some findings from @martinantonmueller 
* the attribute 'subtype' includes spaces and brackets, rendering it invalid
  * can by fixed by using a slug
* place/location has to be placed directly after placeName, in any case before note and idno
* org/idno needs to be before note

also:
the target-value in e.g. `<ptr type="geboren-in" target="https://pmb.acdh.oeaw.ac.at/apis/api2/150"/>`
does not resolve and the target should be https://pmb.acdh.oeaw.ac.at/entity/150/

**Comment by skurzinz** [comment]
This is already tackled by Richard Hadden in a branch that @sennierer merged?

**Comment by martinantonmueller** [comment]
Richard wrote: »Yes, I did some of the work on it (some was done before: I added the annotated texts and a couple of other things). There are still quite a few problems with it, which I'm planning to fix soon«

So I'll update the German language parts of the description
