### ISSUE TITLE
Merged URIs should resolve directly even if merged with other entities

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core#271]
currently URIs from merged entities are not directly resolveable

**Comment by skurzinz** [comment]
this is a possible duplicate of #240

**Comment by sennierer** [comment]
solved in 4c3c5aa50f5e2aaf7d491e9ed8528a7162573168 for the entity uris that are created in the new versions eg https://mpr.acdh.oeaw.ac.at/entity/8243/ needs though still to be solved for the api2 uris, I open another issue for that
