### ISSUE TITLE
API/TEI no output of type

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#277]
https://pmb.acdh.oeaw.ac.at/entity/1/?format=tei

The type of place is not included in the TEI output (should be "Kabarett" in the example), as well as the dates (should be "1901")

**Comment by csae8092** [comment]
could add here an example how it shoud look like?
no we have
```xml
<place xml:id="place__1">
    <placeName notBefore="1901-01-01">Jung-Wiener Theater zum Lieben Augustin</placeName>
    <location>
        <geo>48.19941 16.3642</geo>
    </location>
<note type="persons">
<ptr type="arbeitsort-von" target="https://pmb.acdh.oeaw.ac.at/entity/2167"/>
</note>
<note type="places">
<ptr type="gehort-zu" target="https://pmb.acdh.oeaw.ac.at/entity/56"/>
<ptr type="gehort-zu" target="https://pmb.acdh.oeaw.ac.at/entity/37"/>
</note>
<idno type="URL">https://bahrschnitzler.acdh.oeaw.ac.at/entity/pmb1</idno>
<idno type="URL">https://pmb.acdh.oeaw.ac.at/entity/1</idno>
<idno type="URL">https://schnitzler-briefe.acdh.oeaw.ac.at/pages/hits.html?searchkey=pmb1 </idno>
</place>
```

but it should look like:
???

**Comment by martinantonmueller** [comment]
```
<gloss>Kabarett (K.KBR)</gloss>
<date from='{{start_date_literal}}'>{{start_date_written}}</date>
<date to='{{end_date_literal}}'>{{end_date_written}}</date>
```

**Comment by csae8092** [comment]
so this would be than

```xml
<place xml:id="place__1">
    <placeName notBefore="1901-01-01">Jung-Wiener Theater zum Lieben Augustin</placeName>
    <location>
        <geo>48.19941 16.3642</geo>
    </location>
<note type="persons">
<ptr type="arbeitsort-von" target="https://pmb.acdh.oeaw.ac.at/entity/2167"/>
</note>
<note type="places">
<ptr type="gehort-zu" target="https://pmb.acdh.oeaw.ac.at/entity/56"/>
<ptr type="gehort-zu" target="https://pmb.acdh.oeaw.ac.at/entity/37"/>
</note>
<idno type="URL">https://bahrschnitzler.acdh.oeaw.ac.at/entity/pmb1</idno>
<idno type="URL">https://pmb.acdh.oeaw.ac.at/entity/1</idno>
<idno type="URL">https://schnitzler-briefe.acdh.oeaw.ac.at/pages/hits.html?searchkey=pmb1 </idno>
<gloss>Kabarett (K.KBR)</gloss>
<date from='{{start_date_literal}}'>{{start_date_written}}</date>
<date to='{{end_date_literal}}'>{{end_date_written}}</date>
</place>
```

and I suppose this is valid TEI

**Comment by martinantonmueller** [comment]
at least the new part should be valid. one could become more complex though:

`<xsl:choose>
                            <xsl:when test="start_date_literal = end_date_literal">
                                <xsl:element name="date">
                                    <xsl:attribute name="when-iso">
                                        <xsl:value-of select="start-date-literal"/>
                                    </xsl:attribute>
                                    <xsl:value-of select="start_date_written"/>
                                </xsl:element>
                            </xsl:when>
                            <xsl:otherwise>
                                <xsl:element name="date">
                                    <xsl:attribute name="from-iso">
                                        <xsl:value-of select="start-date-literal"/>
                                    </xsl:attribute>
                                    <xsl:value-of select="start_date_written"/>
                                </xsl:element>
                                <xsl:element name="date">
                                    <xsl:attribute name="to-iso">
                                        <xsl:value-of select="end-date-literal"/>
                                    </xsl:attribute>
                                    <xsl:value-of select="end_date_written"/>
                                </xsl:element>
                            </xsl:otherwise>
                        </xsl:choose>`

**Comment by skurzinz** [comment]
Without a customization this is not valid in `tei_all.rng`: 

- `tei:gloss` is not allowed there
- neither is `tei:date` 

I’d suggest to either customize your schema to define that this is indeed valid (although I don't agree with `gloss` there) or do a proper [https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-listRelation.html](listRelation) that also allows chronological reference.

**Comment by martinantonmueller** [comment]
uj – oopsie! I seem to have messed it up! – Skurz is right, that neither gloss nor date is allowed within place. I don't see any proper way to do a place taxonomy

**Comment by skurzinz** [comment]
It's not a place anyway but an organisation or institution, which eg may have moved to several places... But it's your data modeling 🙂
________________________________
Von: Martin Anton Müller ***@***.***>
Gesendet: Freitag, 23. April 2021 15:41:41
An: acdh-oeaw/apis-core
Cc: Kurz, Stephan; Comment
Betreff: Re: [acdh-oeaw/apis-core] API/TEI no output of type (#277)


uj – oopsie! I seem to have messed it up! – Skurz is right, that neither gloss nor date is allowed within place. I don't see any proper way to do a place taxonomy

**Comment by martinantonmueller** [comment]
Why should a cabaret not be a place? Can I meet you there? Yes I can. Thus it's a place.

**Comment by skurzinz** [comment]
I'd say we can meet at a place (defined by geo coordinates as defined per [`tei:place`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-place.html)), and if at this *place* there happens to be a cabaret (or a theater, or a supermarket, cinema, tree, phone booth, bus stop or any other kind of human-made thing that is bound to some societal action by particular actors which may or may not be known, but nonetheless we can think of as an *institution* – in TEI that is refered to as an [*organization*](https://tei-c.org/release/doc/tei-p5-doc/en/html/ND.html#NDORG)) at the particular point in time we intend to meet there: even better. But as you already have tons of examples for this kind of shortcut, I’ll stop interfering :)

**Comment by martinantonmueller** [comment]
Ah, a discussion! Which of course we will not have! Thank you for your input! Problem is that an organization can have several locations which makes it all the more complicated.

**Comment by skurzinz** [comment]
I wonder what happens if that cabaret place gets turned into a cinema one year later (within your edition’s time frame), and moreover you know that there used to be a restaurant three years before (aptly named "Zum Kabarett" perhaps), while your cabaret with the same name but a different owner was still operating two streets away in the souterrain, after which it slightly rearranged its name a year after when it moved one story up to the ground floor of the same building at the same 2D `geo`. 

Complication may just be the normal way of life.

**Comment by martinantonmueller** [comment]
Actually the cabaret was in the basement of a theatre and yes didn‘t exist long. We have some of those cases. Nevertheless for tracking movement in a city it is necessary to have those locations even if they exist only for a short period of time.

**Comment by csae8092** [comment]
the custom TEI serialisation expresses the type of an entity now as
```xml
<desc type="entity_type">Veranstaltungsgebäude (K.VSB)</desc>
<desc type="entity_type_id">5</desc>
```

see https://pmb.acdh.oeaw.ac.at/apis/entities/tei/place/4
(and yes, the date is still not correct, but at least there is an issue #332)
