### ISSUE TITLE
cannot create relation to entity in db

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#292]
Maybe there was an update to PMB? MacOS Safari is not working properly anymore. When I switched to Chrome (94.0.4606.71) and tried to create a relation between a work and an institution the error message was:

> Invalid value: <span ><small>db</small> Albert Ahn</span>, use either URLs or select a value
<img width="665" alt="Bildschirmfoto 2021-10-11 um 14 06 23" src="https://user-images.githubusercontent.com/11441262/136787644-b8ebcdf2-26a0-4554-9848-e59958c94bef.png">

**Comment by sennierer** [comment]
yes, sorry for that. We moved PMB to the cluster and (re)opened an issue. We resolved it for the other instances, but in PMB is stillan error. Should be fixed soon.
