### ISSUE TITLE
merging issue (old number disappeared)

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#303]
For some reason "Stockholm" got assigned a new PMB-number (62274) and the old one (1119) is not accessible anymore after I merged two entries.

This is what I did:

1. when importing an institution via GND-importer "Stockholm" got a new entry based on GND and not geonames
2. when I noticed the duplicate I went into 62274 and merged it to 1119 

but here the undesired result started:

1. it merged 1119 to 62274 and not the other way round
2. it discarded the previous URI and '1119' can only be deduced from the schnitzler-briefe URI.

now all references to pmb1119 are broken.

**Comment by martinantonmueller** [comment]
seems to be a mistake on my side. Has not been properly merged, I close this issue right away. Sorry for the false alarm!

**Comment by skurzinz** [comment]
You can use https://pmb.acdh.oeaw.ac.at/apis/metainfo/uri/create/ to manually create a reference to the old URI (that's what normally gets done during merging) and then -- if necessary -- adapt your stylesheets to also use the other URI.

**Comment by martinantonmueller** [comment]
I know. I'am a frequent user of that feature. In this very case it is more complicated. But I opened a new issue, see here: https://github.com/acdh-oeaw/apis-core/issues/304
