### ISSUE TITLE
feature-request: make no gender searchable

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#307]
currently it is not possible to list all persons with no value in gender. it would be nice to be able to do so.

**Comment by csae8092** [comment]
@martinantonmueller could you please post a link to an example

**Comment by martinantonmueller** [comment]
I don't know if that changed between me writing this issue and now or if I was too blind to see: But the issue is solved as it is possible to have "Gender" as additional column in the list view.
