### ISSUE TITLE
TEI endpoint: forward for merged entities

### ISSUE THREAD

**Issue by skurzinz** [acdh-oeaw/apis-core#312]
I'm currently trying to implement entity links via MPR for the QhoD project using the generic TEI endpoint.

Merged entities are not forwarded (the generic JSON endpoint is). 
Is it possible to change that? Example: 

https://mpr.acdh.oeaw.ac.at/apis/tei/place/14055 works. 
https://mpr.acdh.oeaw.ac.at/apis/tei/place/14054 or 
https://mpr.acdh.oeaw.ac.at/apis/tei/place/9452 return 404 

Expected behaviour: return same entity data such as in: 

https://mpr.acdh.oeaw.ac.at/entity/14055/
https://mpr.acdh.oeaw.ac.at/entity/14054/
https://mpr.acdh.oeaw.ac.at/entity/9452/

**Comment by csae8092** [comment]
http://127.0.0.1:8000/apis/entities/tei/uri-to-tei?uri=https://schnitzler-briefe.acdh.oeaw.ac.at/pages/hits.html?searchkey=pmb2138

**Comment by skurzinz** [comment]
The solution @csae8092 provided was one to a different problem that was not posed (a lookup in the other direction), pls reopen

**Comment by skurzinz** [comment]
Seems solved. Cannot link to a specific commit, but the forward works now.
