### ISSUE TITLE
label too long, edit buttons not accessible anymore

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#317]
I've added a label with a long URL
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/work/61703/edit

now I cannot access the edit buttons of the labels anymore. maybe if I use a really wide screen though.

basically the problem seems to be fixed-width td’s in labels, that expand over the max width of the label area.

**Comment by sennierer** [comment]
can you please provide more detailed description of the problem: browser, screen resolution and if possible a screen shot? I cant reproduce that behaviour. Even when reducing the width to very small resolutions the label is just wrapped and does not hide the edit button.

![screenshot-pmb acdh oeaw ac at-2022 05 02-11_07_10](https://user-images.githubusercontent.com/499265/166211387-4685e039-be86-4d4c-a5dd-e9b9ae1bd056.png)

**Comment by martinantonmueller** [comment]
I can reproduce it on Firefox and Chrome. It can be seen on your screenshot: The pagewidth is identical with the header-ruler, so the end of the table is outside the active page. A lesser screenwidth than approx. 1380 seems to trigger this behaviou
<img width="782" alt="Bildschirmfoto 2022-05-02 um 11 17 41" src="https://user-images.githubusercontent.com/11441262/166212613-df832841-5bd9-47a5-9683-a40dd5714bf5.png">
r

**Comment by sennierer** [comment]
table stays now within boder of browser also on small devices. On small devices date and iso columns are not shown anymore
