### ISSUE TITLE
Explain better what MERGE button does

### ISSUE THREAD

**Issue by sviatoplok** [acdh-oeaw/apis-core#319]
When merging entities, me and my colleagues all too often merge in the wrong direction and thus destroy the entity that is more important.
--> A clear description (graphic?) what the button does and in WHICH DIRECTION might help.

Also, part of the problem is that it is hard to discern in the displayed entities to merge, which one is which.
I am currently using the workaround to rename the entities temporarily then go back to the merge situation and after merging again rename the entity.
That's time-consuming and annoying.
--> More info in the display of the entities to be merged might help.

**Comment by sennierer** [comment]
added a new issue for the second part
