### ISSUE TITLE
add more data in the autocompletes

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core#321]
currently it is hard to decide from the autocompletes whether you found the correct entity. We will need to add more context information to the autocompletes.
In relation to #319

**Comment by gregorpirgie** [comment]
Added DB and LOD-IDs to Stanbol autocompletes; reformatted autocompletes; removed score from autocompletes. Also reformatted the result string for readability and uniform styling. 

Closed for now with commit [Merge branch 'release/v0.17.12'](https://gitlab.com/acdh-oeaw/apis/apis-core/-/commit/7bad50ed1a40fdf7c0dba1f0cd11fcd49fef7d3c)
