### ISSUE TITLE
fix date TEI serialisation

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/apis-core#332]
https://pmb.acdh.oeaw.ac.at/apis/entities/tei/place/4 -> here it takes start date and start_end date, but for "to" it should take end_end_date, or so

https://pmb.acdh.oeaw.ac.at/apis/entities/tei/institution/36247 -> here it dose not add an start_end_date

its complicated

also do not serialize calculated iso date (like 1.7.1859 for written date 1859) as when-iso attributes

**Comment by martinantonmueller** [comment]
PMB-tei-export: daten werden immer mit bis-strich ausgegeben. könntest du das noch soweit unterscheiden: wenn start- und end-datum gleich, dann wird nur startdatum ausgebeben? ich bereinige das zwar, aber es ist eigentlich besser, das gleich bei der ausgabe zu beheben. beispiel: https://pmb.acdh.oeaw.ac.at/apis/entities/tei/work/52686
