### ISSUE TITLE
in "Kind" field missing ontology entry

### ISSUE THREAD

**Issue by sviatoplok** [acdh-oeaw/apis-core#340]
In "places/Kind" field, the ontology entry

http://www.geonames.org/ontology#T.MT

for "mountain" should be suggested.

**Comment by sennierer** [comment]
I added it. For the records: You can add every vocabulary in the [backenld](https://mpr.acdh-dev.oeaw.ac.at/admin/apis_vocabularies/) . The vocabulary for place type is [here](https://mpr.acdh-dev.oeaw.ac.at/admin/apis_vocabularies/placetype/)

**Comment by sviatoplok** [comment]
Great, good to know.

**Comment by sviatoplok** [comment]
doesn't show up in the list yet, though
