### ISSUE TITLE
EMERGENCY: merge doesn't work

### ISSUE THREAD

**Issue by sviatoplok** [acdh-oeaw/apis-core#341]
When merging an entity into another, server error 500 occurs.
Maybe the same problem as in #304

**Comment by sennierer** [comment]
can you please post the url of the entity you were working on and the search term for the one you tried to merge?

**Comment by sviatoplok** [comment]
occurded eg when merging

> [Serbia](https://mpr.acdh.oeaw.ac.at/apis/entities/entity/place/9423/detail)

into 

> [Serbien](https://mpr.acdh.oeaw.ac.at/apis/entities/entity/place/1478/detail)

**Comment by gregorpirgie** [comment]
Appears to be a self merge, not an issue. Please check if you didn't accidentally try to merge an entity on/with itself.  If otherwise and still an active issue – I am watching this issue here, so please simply post an update and I will look into it @sviatoplok.

**Comment by gregorpirgie** [comment]
Also if not an issue, please report back and I will close it here.

**Comment by sviatoplok** [comment]
OK, same geonames URI, same geo coordinates, insofar it is a self merge.
The goal of merging was to get the URI of the one entry into the other, similar to problem described in #304 
I will try as suggested there.

**Comment by sviatoplok** [comment]
> OK, same geonames URI, same geo coordinates, insofar it is a self merge. The goal of merging was to get the URI of the one entry into the other, similar to problem described in #304 I will try as suggested there.

Could't get the URI of the db entry to be deleted into the db entry I want to keep, because it already exists. Will wait until merge works.

**Comment by sennierer** [comment]
as mentioned here:

> as gregor mentioned this was to the system a self merge, because - at least in the serbia case - both entities had the same geonames uri. The only difference is that one uri uses https, the other http. Probably the http uri was introduced before we came up with the uri harmonization script. Problem is the harmonization we are now using. The system harmonizes the http geonames uri to https and retrieves the wrong object from the db. This is related to #337 , as soon as this is resolved the error should be gone.

this issue should be resolved as #337 is fixed in latest

**Comment by sennierer** [comment]
please reopen if thats not the case

**Comment by skurzinz** [comment]
I tested it now by merging Serbia into Serbien as suggested by @sviatoplok above, and it seems to have worked.
