### ISSUE TITLE
duplicate geonames-ids

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#351]
there are still some issues with the geonames uris – at least in pmb – that should be dealt with from the server-side:

we have geonames-uris with http:// and https:// as well as those with "www." and "sws." thus all in all four different versions creating duplicates

additionally some uris have html in the end: https://sws.geonames.org/2661169/chur.html

**Comment by sennierer** [comment]
I ran a script over the PMB to harmoniye geonames uris. Closing this.
