### ISSUE TITLE
Endpoint for resolving places from GeoNames in map view broken?

### ISSUE THREAD

**Issue by sviatoplok** [acdh-oeaw/apis-core#353]
![grafik](https://user-images.githubusercontent.com/46528983/193566280-751ed601-c0fc-4c83-9b2b-dca46d5dd3f3.png)

Select this URI returns a server error (500) message

**Comment by skurzinz** [comment]
Is ja eh da. https://mpr.acdh.oeaw.ac.at/apis/entities/entity/place/2995/edit

**Comment by sviatoplok** [comment]
war nur ein Beispiel

**Comment by skurzinz** [comment]
Which URI is not working for import? 
Have you tried switching between www. and sws. and https:// and http:// before creating the issue?

**Comment by skurzinz** [comment]
Just tried, and the import works fine with 2 other URIs. Which type of place are you trying to import? Is it a PPLA or an ADM1|2|3? These should work.

**Comment by sviatoplok** [comment]
I was trying to generate an URI from the map in MPR/APIS, as on the picture.

PPLA

**Comment by skurzinz** [comment]
Consultation with @sviatoplok: 

Better issue title would be: **Endpoint for resolving places from GeoNames in map view broken?**

To reproduce: 
- edit any place entity
- in the map view, search for any placename
- try clicking on "select this URI", which does e.g. https://mpr.acdh.oeaw.ac.at/apis/entities/resolve/place/1447/sws.geonames.org/3068799/ 
- this returns 500

(I did not even know you could click around on the map, hence my now deleted questions to the OP in the thread, sorry.)

**Comment by sennierer** [comment]
this is now resolved, but we might want to re-consider how: The errors were only when the object with the selected uri already existed. I switched that now from `create` to `get_or_create`. However, that means also that you might end up with merges you dont want (as you dont know from the map view that this object already exists in the db)
