### ISSUE TITLE
implement a detail-view redirect

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/apis-core#361]
entity with id 123 is merged into entity 321; but ID 123 is already referenced somewhere; therefore a link to the entity GUI detail view e.g. `https://pmb.acdh.oeaw.ac.at/apis/entities/entity/work/123/detail` returns a 404 but it would be nice to implement a redirect to `https://pmb.acdh.oeaw.ac.at/apis/entities/entity/work/321/detail` which should be possible as the 'old' ID is kept in one of the new entities URIS

**Comment by zozlak** [comment]
It would be great also to:

* make the redirect work for `https://pmb-service.acdh-dev.oeaw.ac.at/arche/{oldId}`
* report the old id among `acdh:hasIdentifier` in `https://pmb-service.acdh-dev.oeaw.ac.at/arche/{currentId}`

**Comment by csae8092** [comment]
> It would be great also to:
> 
>     * make the redirect work for `https://pmb-service.acdh-dev.oeaw.ac.at/arche/{oldId}`
> 
>     * report the old id among `acdh:hasIdentifier` in `https://pmb-service.acdh-dev.oeaw.ac.at/arche/{currentId}`

see https://github.com/arthur-schnitzler/pmb-service/issues/28

**Comment by zozlak** [comment]
Sorry, commented in wrong issue (facepalm).

**Comment by zozlak** [comment]
Thanks!
