### ISSUE TITLE
if `entity/{id}` called via webbrowser it should redirect to entities detail view

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/apis-core#370]

**Comment by skurzinz** [comment]
Q: Does that make sense? Are there any applications using links of this type to fetch information? Will there be any possibility to still get the raw data from the browser (for checking, debugging etc purposes)?

**Comment by csae8092** [comment]
> Q: Does that make sense? Are there any applications using links of this type to fetch information? Will there be any possibility to still get the raw data from the browser (for checking, debugging etc purposes)?

Yes it make sense as we will use the `entity` link e.g. in ARCHE or all Schnitzler-Kraus... Projects because
* they are much easier to deal with or to construct from a single ID than `https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/2142/detail`
* if you are on a website it is much more likely that users want to see a GUI output than some probably arcane data format (which for some entities also might take ages to load)

And yes, you can overrule the content negotiation by adding either the already existing format param, or by adding a newly implemented `?data-view=true` param (this is e.g. used in an entities detail view, so that you can link in the browser to the entities data view)

(see also https://github.com/acdh-oeaw/apis-core/pull/374#issue-1443664872)

**Comment by skurzinz** [comment]
Ok ok, sorry, did not fully read the comment you just linked to :)
