### ISSUE TITLE
update contact info

### ISSUE THREAD

**Issue by sviatoplok** [acdh-oeaw/apis-core#38]
Currently, the contact info reads 

> IKT

> Institute of Culture Studies and Theatre History of the Academy of Sciences
Austrian Academy of Sciences

**Comment by sviatoplok** [comment]
Test comment.

**Comment by csae8092** [comment]
done with commit https://github.com/acdh-oeaw/paas/commit/f71c05680673a856af76f48acec41f53b4d89ff3

**Comment by sviatoplok** [comment]
:-)
