### ISSUE TITLE
When opening a person entity, unfold Metadata Person

### ISSUE THREAD

**Issue by sviatoplok** [acdh-oeaw/apis-core#39]
When opening a **person** entity, unfold the **Metadata Person** area and set first tab stop to Name field.

**Comment by csae8092** [comment]
https://github.com/acdh-oeaw/apis-core/commit/1272635a89fb61a6f380e80576cd7b98984eb473 -> Metadata Field is unfolded

**Comment by sviatoplok** [comment]
Great, can you just set the tab on tab stop  "NAME" on opening?

**Comment by sviatoplok** [comment]
I mean, set the cursor position on the NAME tab stop?
