### ISSUE TITLE
false positive when accessing TEI-export

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#392]
To access the TEI-export I use this URL:

https://pmb.acdh.oeaw.ac.at/apis/entities/tei/org/50

where the last number is the entry-number. Problem is: I can use any existing entity number in the database, not just org-numbers, and get a TEI-result.

**Comment by gregorpirgie** [comment]
This should be an easy fix. At the moment all tei-endpoints fetch each object only by id and don't check if the object is actually an instance of the requested entity. 

So this problem not only applies to orgs.

**Comment by gregorpirgie** [comment]
@martinantonmueller  As I personally haven't used this endpoint yet: Is my assumption correct that orgs in the TEI-endpoint are Institutions in the apis-datamodell? And that instance of the Institution-Model, regardless the instance's  kind (Institution-kind), should be a valid return value for the org-endpoint?

If my assumption is correct I will implement a check in each endpoint if the requested object is an instance of the expected entity or otherwise return a 404-Error. This would be the desired behaviour, right?

**Comment by csae8092** [comment]
> @martinantonmueller or @csae8092 – As I personally haven't used this endpoint yet: Is my assumption correct that orgs in the TEI-endpoint are Institutions in the apis-datamodell? And that each instance of the Institution-Model, regardless of the instance's kind (Institution-kind), should be a valid return value for the org-endpoint?
> 
> If my assumption is correct I will implement a check in each endpoint if the requested object is an instance of the expected entity or otherwise return a 404-Error. This would be the desired behaviour, right?

yes, org is the tei equivalent of an apis-institution; and your entity-type check would work for me as well, so green light from my side, Thanks!

**Comment by martinantonmueller** [comment]
yes, your assumption is correct, it is wrong for all entity types, I can use 
https://pmb.acdh.oeaw.ac.at/apis/entities/tei/person/50
as well even though only "place/50" should lead to an output

**Comment by csae8092** [comment]
> yes, your assumption is correct, it is wrong for all entity types, I can use https://pmb.acdh.oeaw.ac.at/apis/entities/tei/person/50 as well even though only "place/50" should lead to an output

@martinantonmueller as you are mainly the only user of this endpoint, are you ok with the proposed solution which would return a 404-error for something like https://pmb.acdh.oeaw.ac.at/apis/entities/tei/person/50 ?

**Comment by martinantonmueller** [comment]
yes, sure!

**Comment by gregorpirgie** [comment]
Added a pull-request with fix and assigned @csae8092 as reviewer. Should be ready to merge.

**Comment by gregorpirgie** [comment]
Alright, makes sense. Didn't know about that reasoning.
