### ISSUE TITLE
landing page with dummy text

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#397]
[PMB](https://pmb.acdh.oeaw.ac.at/)
currently looks like this:
<img width="965" alt="Bildschirmfoto 2023-06-09 um 08 51 03" src="https://github.com/acdh-oeaw/apis-core/assets/11441262/3ff6a0f1-468b-40b0-9136-1fbfa70863cc">

For whatever reason I don’t know. Maybe the server-crash last week?

**Comment by csae8092** [comment]
fixed via redeploy
