### ISSUE TITLE
Set tab stops in relations

### ISSUE THREAD

**Issue by sviatoplok** [acdh-oeaw/apis-core#40]
When editing **relations**, after entering **relation type**, set institution/place/person/etc. entry field as next tab stop.
Do the same for subsequent fields.

**Comment by sviatoplok** [comment]
Great, thanks! Could you make 'relation type' the first tab stop (instead of 'delete')?

**Comment by sviatoplok** [comment]
MISUNDERSTANDING:
currently, the focus is on "delete", not on "relation type"
"delete" is the first element but it would save more work if you would set focus on the first _entry_ field, which is "relation type"
the same goes for PERSON and PLACE

**Comment by sennierer** [comment]
Yes. Actually that is the case now. However the code is not yet running on the production instance, but you can check it in the development instance.
