### ISSUE TITLE
allow tabulator to leave the MetaInfo fold-out

### ISSUE THREAD

**Issue by sviatoplok** [acdh-oeaw/apis-core#42]
When editing/creating an entity, in fold-out menu **MetaInfo / Collection** allow tabulator to leave the fold-out.

**Comment by sennierer** [comment]
Could you specify that: When editing an entity in the left pane you can use tab to run through all the form fields including the metainfo. It is also possible to leafe the metainfo and go to the create/modify button with tab.

**Comment by sviatoplok** [comment]
this issue is not important to improving the workflow any more as with the metadata prefilled I don't need the metadata on a regular basis anymore
