### ISSUE TITLE
fix field order and make titles consistent in start view and edit view

### ISSUE THREAD

**Issue by sviatoplok** [acdh-oeaw/apis-core#44]
field order in start screen is different from edit/create screen

It's `Name, Start, End, Status, First name` vs. `Name complete, First Name, Gender, Date of birth, Date of Death`

Also, the field titles are inconsistent. `Name` vs. `Name complete` and `Start` vs. `Date of birth` etc.

**This is confusing and it slows down my workflow.**

**Comment by csae8092** [comment]
@sviatoplok  what would be your preferred order? Something like this:
```
'name',
'first_name',
'gender',
'profession',
'title',
'start_date',
'end_date',
'status'
```

**Comment by csae8092** [comment]
I applied some changes in the test version https://mpr.acdh-dev.oeaw.ac.at/apis/entities/entity/person/1404/edit

**Comment by sviatoplok** [comment]
'name',
'first_name',
'gender',
'title',
'profession',
'start_date',
'end_date',
'status'

**Comment by csae8092** [comment]
changed it https://github.com/acdh-oeaw/apis-core/commit/387ac033f363f4675c896a93fd761d5301c6e7d1
