### ISSUE TITLE
enable default collection on creation of entity

### ISSUE THREAD

**Issue by skurzinz** [acdh-oeaw/apis-core#45]
Data entry workflow related: 
It would make sense to set a default collection on creation through the web interface (in our case: mpr.acdh-dev... this would be the "Manuell erstellte Entität" collection). Saves one more click per entity :)

**Comment by skurzinz** [comment]
actually, it is four clicks.

**Comment by csae8092** [comment]
provide settings param: name of default collection for manually created objects

**Comment by sviatoplok** [comment]
it's "Manuell erstellte Entität"
