### ISSUE TITLE
allow to set attributes to show in list view

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core#49]
similar to https://github.com/reading-in-the-alps/ and https://github.com/acdh-oeaw/djangobaseproject we should allow to set the attributes to show in the list tables. We can store that setting in the sessions variables

**Comment by csae8092** [comment]
basically done, configuration is stored in APIS_ENTITIES dict; one thing left to do, provide some list of shared fields to spare duplications....
