### ISSUE TITLE
person surname etc search variants

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#76]
the search field for surname does not find any alternative surnames e.g married names. consider
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/29185/edit
she has a label geboren-geboren 
named Patzner
but you won't find her if you search Patzner

**Comment by csae8092** [comment]
@sennierer  I guess this is can be customized in project-settings

**Comment by sennierer** [comment]
there is a setting called APIS_ALTERNATE_NAMES that holds the labels that are used for alternative names.
So simplest solution would be APIS_ALTERNATE_NAMES += ["geboren",]

**Comment by csae8092** [comment]
fixed with [commit](https://github.com/acdh-oeaw/apis-webpage-base/commit/8a7d179213cb4756c26e46d393f820f9b31fbd4e)
Patzner Mimi is found by
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/list/?name=Patzner&first_name=&gender=&start_date=&end_date=&Filter=Filter
