### ISSUE TITLE
place place relation

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#81]
Can't create relation

See
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/33903/edit
Tänzelgasse
which would belong to Bad Ischl but I can't create a relation

**Comment by csae8092** [comment]
this is a known bug and already fixed, just waiting for the next apis_core release so I can update pmb-apps

**Comment by sennierer** [comment]
just uploaded a new version with all the improvements of recent days. The bug should be resolved.
