### ISSUE TITLE
Merge: Don't show the entry currently selected to merge

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#83]
If I have a duplicate like this:
Millöcker, Carl
Millöcker, Karl
and choose Carl and select "Merge" i start to type and other persons in the db show. It should only show "Millöcker, Karl" but it shows both, Carl and Karl. (I.e. I could merge an entry with itself)

**Comment by skurzinz** [comment]
+1  for solving this rather urgently! 

In addition: Merging an entity with itself results in a deleted entity. 

In the dropdown, pls omit the entity with the current id, and include the entity ID for reference.
