### ISSUE TITLE
Buttons order

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#84]
On the detail-page of an entity: The "modify"-Button i.e. save after the delete-button is bound to have unwanted results. the "create new work" does not make sense here as it is unclear whether this would save the current changes or discard them.

Suggestion:
Modify -> First button
Revisions -> Second
Delete -> Third

**Comment by csae8092** [comment]
changed button order as requested with https://github.com/acdh-oeaw/apis-core/commit/3c6b31e9654572d9a48b4540160bfcf62c47a791
the 'create new {entity}' was requested by other users and it would NOT save the current modification but open a blank form to create a NEW entity
