### ISSUE TITLE
Pager (person work-relation)

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#90]
https://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/11988/edit?PeWo-page=2
If i open a person, i.e. Karl Kraus, and the person has more work-relations than what fits unto a single page, the pager is missing blanks, i.e.:

> zurück123weiter

instead of

> zurück 1 2 3 weiter

and when second page is chosen, the page reloads without showing the second page. only after one opens the "work" relations field one sees the second page

**Comment by sennierer** [comment]
resolved by specifying a bootstrap template for tables2 tables in https://github.com/acdh-oeaw/apis-webpage-base/commit/66e7cfc89cb95a440d6a50ff098e7f1515536b4b
