### ISSUE TITLE
Article (grammar) at the beginning of works

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#96]
To find Goethes »Die Wahlverwandtschaften« I currently have to know the title in order to get a result. So
»Die W*« has the desired output
»Wahlv*« does not
Same as: »Eine kleine Nachtmusik« could not be found by
»Nachtmusik« or »Nachtm*«
That would be a nice feature to have!

**Comment by sennierer** [comment]
*wahl* finds "Die Wahlverwandschaften".
We will add help texts to make explicit how the search works

**Comment by steffres** [comment]
It does work by appending a `*` in front as well, such as: `*Wahlv*`
