### ISSUE TITLE
Error page

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/apis-core#97]
When viewing Therese Reinhard I created a relation between Therese Reinhard and Carl Reinhard ("Ehepartner"). Then I selected Carl Reinhard in the newly created relation and was shown his entry. I tried to fill out his sex ("male") but this error-page came:

> 
> Request Method: | POST
> -- | --
> http://pmb.acdh.oeaw.ac.at/apis/entities/entity/person/23209/edit
> 2.1.2
> NoReverseMatch
> Reverse for 'generic_entities_create_view' with arguments '('',)' not found. 1 pattern(s) tried: ['apis/entities/entity/(?P<entity>[a-z]+)/create$']
> /var/www/html/myenv/lib/python3.6/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 622
> /usr/bin/python3
> 3.6.7
> ['/var/www/html',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  '/var/www/html',  '/var/www/html/myenv/lib/python3.6/site-packages',  '/var/www/html/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/myenv/lib/python3.6/site-packages/odf',  '/var/www/html/myenv/lib/python3.6/site-packages/odf']
> Di, 9 Apr 2019 10:27:20 +0000
> 
>

**Comment by csae8092** [comment]
good to know, 
one thing is to turn of the debug mode, the other thing I happily fast forward to @sennierer
